### ISSUE TITLE
Determine framework JavaScript

### ISSUE THREAD

**Issue by skoolbus39** [d-c-n/dcf#10]
Use [jQuery](http://jquery.com/) or [plain](http://youmightnotneedjquery.com/), [vanilla](https://css-tricks.com/now-ever-might-not-need-jquery/) JavaScript? 

Should we compile JavaScript with [Babel](https://babeljs.io/)?

**Comment by tlemburg** [comment]
I vote continue to use jQuery. jQuery is known by almost every web developer and while it does add a few bytes to the page it's not prohibitive.

**Comment by Shaderpixel** [comment]
Is there a way, to make it an opt-in for jQuery? I can see sites that have no dependency on jQuery or devs that can write vanilla JS benefit from the lack of jQuery? Just a thought. Also ES6 stuff will be nice. Ultimately, we shouldn't let the rewriting of each existing jQuery dependent component into vanilla JS hinder progress of DCF or 5.0, a phased process might be worth a consider? Also, how performant are the components that are relying on jQuery? Is there a list of all the jQuery dependent components being used out there?
