### ISSUE TITLE
Determine webfont loading strategy

### ISSUE THREAD

**Issue by skoolbus39** [d-c-n/dcf#16]
The framework must be flexible enough to account for differences in webfont hosting services between the institutions. For example, UNL uses [Cloud.typography](https://www.typography.com/cloud/welcome/), which loads fonts differently than [Typekit](https://typekit.com/) or [Google Fonts](https://fonts.google.com/).

**Comment by tlemburg** [comment]
This will be very difficult to abstract entirely. It would likely come down to giving each participant complete control over the head tag, which is fine, but may cause troubles with loading "speedy"-like templates and so on. Perhaps there is some sort of library out there that lets one pick a webfont provider and injects code from there. If not, maybe we make one.
