### ISSUE TITLE
Overcoming issue of displaying tables in a narrower screen size without making i

### ISSUE THREAD

**Issue by Shaderpixel** [d-c-n/dcf#173]
Current responsive methods of displaying tables in narrower screen sizes either 

1. removes the visual table look and feel on mobile to render it in a single column-like format
2. keep it in its original format like in desktop but apply `overflow-x: scroll` to the table wrapper

**Method 1
Benefit: Visually more pleasing, presents data in readable format
Issue: Mobile-presented information might lose its hierarchical representation in an actual table when broken down into a column-like format on mobile

**Method 2
Benefit: Retains visual hierarchical & tabular representation of an actual table  
Issue: Often there is insufficient indicator/hint to let users know that they can scroll horizontally on mobile to view the full table

Suggestion to improve method 2: Associate a progress element `<progress>` and use JS to capture the current scroll point and use a gradient outline/border on the table element when it is in focus or active to also indicate whether the table has been fully scrolled

**Comment by skoolbus39** [comment]
Fixed by #257.
