### ISSUE TITLE
Choose JavaScript module loader

### ISSUE THREAD

**Issue by skoolbus39** [d-c-n/dcf#7]
- [Webpack](https://webpack.js.org/)?
- [RequireJS](http://www.requirejs.org/)?
- [Browserify](http://browserify.org/)?
- [StealJS](https://stealjs.com/)?
- something else?

**Comment by tlemburg** [comment]
For module loading, Webpack is probably not a good idea as it is a "static module bundler". We want something a little more dynamic, so let's stick with RequireJS for the module loading.
